language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis 서버 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean bootJar"

# CI 실행 완료시 메일 알림
notifications:
  email:
    recipients:
      - ndsrhkd98@gmail.com